TomEE 7.1.4-TT.2
tomitribe/tomee pull request #133
Opened 2020-10-20 22:46 UTC by cesarhernandezgt

2020-10-21 10:46 UTC, jgallimore commented on tomee/apache-tomee/src/main/resources/META-INF/release_notes/RELEASE-NOTES-EAP-7.0.x
> +* Update ActiveMQ to mitigate CVE-2020-11998 and CVE-2020-11998
Can you correct this line (you might need to find out the right CVE number for the second one)

2020-10-21 10:47 UTC, jgallimore requested changes
Just one small change on the release notes. Otherwise looks fine.

2020-10-21 16:19 UTC, cesarhernandezgt commented on tomee/apache-tomee/src/main/resources/META-INF/release_notes/RELEASE-NOTES-EAP-7.0.x
> +* Update ActiveMQ to mitigate CVE-2020-11998 and CVE-2020-11998
Good catch, done in e00cc10

2020-10-22 09:22 UTC, jgallimore approved these changes

2020-10-22 09:29 UTC, merged